version: '2'

services:
  php:
    build: apps
    ports:
      - "30080:80"
      - "30443:443"
    volumes:
      - ./apps/Samurai-Dojo/basic:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=samurai
      - MYSQL_DATABASE=samurai_dojo_basic
